import { BrowserRouter as Router, Routes, Route, useLocation } from 'react-router-dom';
import { AnimatePresence } from 'framer-motion';
import ScrollToTop from './components/ScrollToTop';

// Views
import HomePage from './pages/HomePage';
import CityGuideView from './pages/CityGuideView';
import PrivacyPolicyView from './pages/PrivacyPolicyView';
import TermsOfServiceView from './pages/TermsOfServiceView';
import TravelDisclaimerView from './pages/TravelDisclaimerView';
import SystemSpecsView from './pages/SystemSpecsView';
import SecurityProtocolView from './pages/SecurityProtocolView';

// Components
import PageTransition from './components/PageTransition';
import Footer from './components/Footer';

/**
 * AnimatedRoutes Component
 * We use location.key in addition to pathname to force a re-animation 
 * even when navigating to the current URL (e.g., clicking Home while on Home).
 */
function AnimatedRoutes() {
  const location = useLocation();

  return (
    <AnimatePresence 
      mode="wait" 
      onExitComplete={() => {
        // Ensure we are at the top before the new page reveals
        window.scrollTo(0, 0);
      }}
    >
      {/* The secret for same-page transitions: 
        location.key is a unique string generated by React Router for every navigation event.
      */}
      <Routes location={location} key={location.pathname + location.key}>
        {/* Main Entry Point */}
        <Route 
          path="/" 
          element={
            <PageTransition>
              <HomePage />
            </PageTransition>
          } 
        />

        {/* Dynamic City Guide */}
        <Route 
          path="/guide/:slug" 
          element={
            <PageTransition>
              <CityGuideView />
            </PageTransition>
          } 
        />

        {/* Protocol Pages */}
        <Route 
          path="/specs" 
          element={
            <PageTransition>
              <SystemSpecsView />
            </PageTransition>
          } 
        />
        <Route 
          path="/security-protocol" 
          element={
            <PageTransition>
              <SecurityProtocolView />
            </PageTransition>
          } 
        />

        {/* Compliance Pages */}
        <Route 
          path="/privacy" 
          element={
            <PageTransition>
              <PrivacyPolicyView />
            </PageTransition>
          } 
        />
        <Route 
          path="/terms" 
          element={
            <PageTransition>
              <TermsOfServiceView />
            </PageTransition>
          } 
        />
        <Route 
          path="/disclaimer" 
          element={
            <PageTransition>
              <TravelDisclaimerView />
            </PageTransition>
          } 
        />
      </Routes>
    </AnimatePresence>
  );
}

export default function App() {
  return (
    <Router>
      <ScrollToTop /> 
      <div className="flex flex-col min-h-screen bg-[#F7F7F7]">
        {/* Main Content Area: flex-grow ensures footer is pushed to bottom */}
        <main className="flex-grow">
          <AnimatedRoutes />
        </main>
        
        {/* Global Footer 
          Navigation triggered here now resets the transition state 
          regardless of the current route.
        */}
        <Footer />
      </div>
    </Router>
  );
}